apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/justmeandopensource/argocd-demo.git
    targetRevision: HEAD
    path: yamls
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
